platform :ios, '9.0'

target 'CameraOpus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'SSZipArchive'
    pod 'Socket.IO-Client-Swift', '~> 15.1.0'


  # Pods for CameraOpus

  target 'CameraOpusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CameraOpusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
